version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          name: Restore Yarn packages cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - save_cache:
          name: Save Yarn packages cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Check types
          command: yarn run check-types

      - run:
          name: Lint
          command: yarn run lint
